apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-asj8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-asj8
    app.kubernetes.io/part-of: ci1t-830-0061-app
  name: devfile-sample-asj8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-asj8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-asj8
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0061-tenant/ci1t-830-0061-app/devfile-sample-asj8@sha256:7bad7b78dfc121b1f9c4146b5988661b4446095ce64483ef760c38d06933a55d
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
